language: ruby
dist: trusty
cache: bundler
bundler_args: --without tools
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.7
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE=true
addons:
  code_climate:
    repo_token: 2c92f1dc6b512f11d06153bcf2f3f5b507af6faa95b3319f559bae1a6bcb2c1a
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
